[tools]
rojo = "rojo-rbx/rojo@7.2.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
selene = "kampfkarren/selene@0.25.0"
wally = "upliftgames/wally@0.3.1"
StyLua = "JohnnyMorganz/StyLua@0.17.0"
