[package]
name = "chriscerie/react-error-boundary"
description = "A robust error boundary library for Lua React."
version = "0.2.0"
license = "MIT"
authors = ["chriscerie"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@^0.4"
React ="jsdotlua/react@^17"
ReactRoblox = "jsdotlua/react-roblox@^17"
LuauPolyfill = "jsdotlua/luau-polyfill@^1.2"
Collections = "jsdotlua/collections@^1.2"
Sift = "csqrl/sift@^0.0"
